# This is a basic workflow to help you get started with Actions

name: update

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allows you to run this workflow manually from the Actions tab
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  make:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up Node.js version 20.10.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo runnning...

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Runs a test script
      - name: Run a script
        run: npm run start

      # Upload artifact for deployment job
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist
    
  build:
    needs: make
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4